### ISSUE TITLE
Re-indexing of all data after upgrading to 2.0.0

### ISSUE THREAD

**Issue by stmyers** [jorritfolmer/TA-dmarc#1]
I upgraded to 2.0.0 and all the reports are getting re-indexed.

**Comment by jorritfolmer** [comment]
Yeah apologies, I should have made it much clearer in the changelog:

- that the 2.0.0 release has breaking changes compared to the 1.2.1 (currenly only implied)
- what the consequences of these changes are after upgrading

It's a one time thing though as everything is now much better kept in KVstore.
You can inspect the contents with `|inputlookup ta_dmarc_checkpointer_lookup`

**Comment by jorritfolmer** [comment]
I've added a warning to the release notes on Splunkbase.
