### ISSUE TITLE
XSD validation

### ISSUE THREAD

**Issue by jorritfolmer** [jorritfolmer/TA-dmarc#10]
The development of XSD validation in TA-dmarc went something like this:

1. v2.1.0:
    - Check: against rua.xsd downloaded from dmarc.org
    - Report: failure/success as 1 additional field in the output. 
    - Observations: Lots of reports failed validation based on this XSD
2. v2.4.0
    - @malvidin swapped the XSD for the newer one in RFC7489
    - Report: failure/success as 1 additional field in the output. 
    - Report: validation error text as 1 additional field in the output, so we can see why validation failed
    - Observations: Still validation errors from reputable reporters, but much less

Questions that emerge:

1. What are our views on rejecting reports on XSD validation failure? At what point do we start rejecting them?
2. What are our views on a "relaxed" XSD, for example to accommodate benign validation errors from reputable reporters?

Any other questions that we need to address?

**Comment by jorritfolmer** [comment]
Here are my views:

1. We shouldn't reject invalid reports, but present factual metadata for others to base this decision on.
    - Reasoning: as a Splunk technical add-on we're in the business of collecting data. Processing the data into information should take place in Splunk apps or dashboards. Analysing this information and converting it into intelligence is the last step, probably done by humans. 
    - Example: Rejecting invalid reports kills the possibility to research standards compliance of reporters throughout the years, or other uses we haven't yet foreseen.
2. We should upgrade our XSD validation logic to include multiple checks, of which a relaxed XSD can be one.
    - Reasoning: By providing factual validation results we give processors better data to base decisions on. A single relaxed XSD is too opinionated. If you want to exclude invalid reports, you can. If you want to include them, because reasons, you can too.

**Comment by malvidin** [comment]
My opinion:

1. We should reject reports that do not include any DMARC information. We already reject files that aren't certain types or have certain file extensions, and have exceptions for other compression types. Using an XSD to validate the XML is not necessary, but we still need some check that it contains some sort of DMARC aggregate report.

2. I also prefer multiple validation checks, with a user selected level of verbosity and chosen validation XSD files.

In the future, it may be useful to include instructions to add custom XSDs.

To clarify, I added two additional XSD files to supplement the XSD from DMARC.org. One is the XSD from RFC7489 Appendix C and the other is a relaxed XSD to validate reports that don't match either strict XSD (Google, Splunk, etc.).

**Comment by jorritfolmer** [comment]
1. Agreed, we should reject non-DMARC stuff. 
Proposal: we use ta_dmarc_minimal_v01.xsd (below) to reject. This successfully rejects the various XML files in a Word document, which for the purposes of the test I've renamed from document1.docx to document1.zip.

   ````
    <?xml version="1.0"?>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="feedback"/>
    </xs:schema>
   ````
2. Proposal for the default validation set, with outputs in some JSON object(s):
    - draft-dmarc-base-00-02.xsd (this appears to be the one from https://dmarc.org/dmarc-xml/0.1/rua.xsd)
    - rfc7489.xsd (appendix c)
    - ta_dmarc_relaxed_v01.xsd (yours)

**Comment by malvidin** [comment]
Current validation flow as I understand it:

1. Reject reports that fail ''ta_dmarc_minimal_v01.xsd' validation of the root element, 'feedback'
    1. For failed files, do we want to log the failed filename and the validation information?
    2. Is it appropriate to use available email and/or file data for the Splunk 'source' for all processed files?

2. Reject reports that omit 'report_metadata', 'policy_published', or 'record'
    1. Include version, if available

3. Validate with multiple XML validation schema, but allow compressed IPv6
    1. Return the most strict validation passed, listed below in decreasing strictness:
        1. 'rfc7489.xsd'
        2. 'draft-dmarc-base-00-02.xsd'
        3. 'ta_dmarc_relaxed_v01.xsd'
     2. Also return the errors for the most lenient validation that failed.
        1. Rename 'vendor_rua_xsd_validation_error' to 'vendor_rua_xsd_validation_info'
        2. [ 'rfc7489.xsd'; 'success' ]
        3. [ 'draft-dmarc-base-00-02.xsd'; 'xsd validation failed for file ./data/splunk_rua.xml with Element 'version': This element is not expected. Expected is ( report_metadata )., line 3' ]
        4. [ 'ta_dmarc_relaxed_v01'; 'xsd validation failed for file ./data/splunk_rua.xml with Element 'sp': [facet 'enumeration'] The value '' is not an element of the set {'none', 'quarantine', 'reject'}., line 19' ]

**Comment by jorritfolmer** [comment]
1. Reject reports that fail ta_dmarc_minimal_v01.xsd:
    i. I think we should log as much as possible
    ii. good idea

2. Reject reports that omit report_metadata, policy_published or record:
   i. Agreed, but I cant seem to create an XSD that checks if these 3 fields exits, but doesn't fail if there are more fields included like "version" or future enhancements like "signature", or "x509". We can implement it in code instead if the xsd route is a dead end.

3. Validate with multiple XSDs
    i. I think we should include the results from every validation in a new tbd object, so we can report on them individually like this:
    <img width="937" alt="screen shot 2018-01-01 at 18 55 38" src="https://user-images.githubusercontent.com/11555154/34469729-79cc840a-ef25-11e7-86f0-6927c7659c84.png">
    And:
    <img width="847" alt="screen shot 2018-01-01 at 18 57 46" src="https://user-images.githubusercontent.com/11555154/34469743-becd2e7e-ef25-11e7-8c3e-d8b67ab8a676.png">

    tbd object under feedback root:

```
"vendor_rua_xsd_validations": [
{
  "rua_draft-dmarc-base-00-02.xsd": {
    "result": "pass"
    "info": ""
   }
},
{
  "rua_rfc7489.xsd": {
    "result": "fail",
    "info": "blah error element not expected"
  }
},
{
  "rua_ta_dmarc_relaxed_v01.xsd": {
    "result": "pass",
    "info": "blah error not one of a b c"
  }
}]
```

Perhaps we should also think about the other content checks you mentioned, and look at how we would fit that in.

**Comment by malvidin** [comment]
Sounds good. 

For email and file information, I do not believe that I will be able to process the email, only the file. I do not have IMAP access, the final file delivery is through a different path.

For report_metadata, policy_published and record checking, I tried to get the XML validation with similar results and found related issues about [UPA](https://en.wikipedia.org/wiki/Unique_Particle_Attribution). I haven't found XSD 1.1 implemented in Python. I have not checked if a different lxml validation (DTD, Schematron, etc.) can provide that capability.

I expect that trying each of the following would be simpler.
xmldata.find('version')
xmldata.find('report_metadata')
xmldata.find('policy_published')
xmldata.find('record')

I accidentally left in the anchors (^,$), but I hope that [this request ](http://www.rfc-editor.org/errata/eid5221) can help fix the IPv6 validation. Either way, I prefer to use the 'relaxed' IPv6 validation for all XML validation.

**Comment by malvidin** [comment]
Looks like [ambiguity in the RFC](http://www.rfc-editor.org/errata/eid5229C) may be causing some of the validation problems for Splunk aggregate reports.

**Comment by jorritfolmer** [comment]
Validation failures for 'sp' appear to be quite common. Got another one from a large Dutch org. (My _dmarc IN TXT record doesn't contain an sp).

**Comment by jorritfolmer** [comment]
Looks like we've implemented everything on the wishlist as discussed.
