### ISSUE TITLE
Relaxed Validation XSD Review

### ISSUE THREAD

**Issue by malvidin** [jorritfolmer/TA-dmarc#13]
At least 264 reports I received contained 7 distinct validation errors with the relaxed XSD (v2.5.1).

Additional review of the reports and the XSD are needed to determine if some of the reports should pass relaxed validation.
- The errors for "unknown", "error", and "Pass" are easily addressed (and mentioned in the RFC XSD comments)
- The order of DKIM and SPF in a result could be ignored
- The subdomain policy should be made optional
- The failure reporting format doesn't matter much for an aggregate report, but why not accept it in the policy published?

This leaves two that I don't think should pass relaxed validation.
- A report with a "X.X.X.X" IP address
- An "auth_results" without an SPF, when "There will always be at least one SPF result"

[relaxed_xsd_info.xlsx](https://github.com/jorritfolmer/TA-dmarc/files/1615929/relaxed_xsd_info.xlsx)

**Comment by jorritfolmer** [comment]
Agreed!

Does the "X.X.X.X" IP address by any change come from an EU-based org?
Perhaps some GDPR data minimization principle at work?

**Comment by malvidin** [comment]
It looks like the address came from a US company from Virginia. It doesn't provide much value without an SPF or DKIM pass result.

    <row>
      <source_ip>X.X.X.X</source_ip>
      <count>1</count>
      <policy_evaluated>
        <disposition>none</disposition>
        <dkim>fail</dkim>
        <spf>fail</spf>
      </policy_evaluated>
    </row>

It could be a very cheap and frustrating interpretation of GDPR. Without more information, I can't tell.

**Comment by malvidin** [comment]
Based on the email headers, the report the contains "X.X.X.X" is generated by "SecurityGateway for Email Servers". I didn't find any documentation about hiding IP addresses on their website. http://www.altn.com/Products/SecurityGateway-Email-Firewall/

**Comment by malvidin** [comment]
Current validations appear to be sufficient. If other significant errors are found, those issues can be raised then.
