### ISSUE TITLE
XML Parsing Error Review

### ISSUE THREAD

**Issue by malvidin** [jorritfolmer/TA-dmarc#14]
Observed XML Parse Errors:
- validate_xml: xml parse error for file <filename> with Unsupported encoding windows-1252, line 1, column 44
   - TA-dmarc needs to parse XML with other character sets
   - Domain(s): aol.com
- is_valid_rua_xmlfile: XML parse error in file <filename> with exception not well-formed (invalid token): line 5, column 10
   - "<>" in the email field
   - Domain(s): uwaterloo.ca
- is_valid_rua_xmlfile: XML parse error in file <filename> with exception not well-formed (invalid token): line 1, column 44
   - Double quote (") after <?xml version="1.0"?>
   - Domain(s): sitnet.dk, ikea.com
  
I think that only the first issue is best resolved by TA-dmarc.

**Comment by jorritfolmer** [comment]
Interesting! Can you add an anonymised windows-1251 encoded sample to the data/ dir?

**Comment by malvidin** [comment]
I uploaded it to a new branch, [aol_rua](https://github.com/malvidin/TA-dmarc/blob/aol_rua/bin/dmarc/test/data/aol_rua.xml).

**Comment by malvidin** [comment]
I didn't get the encoding error doing the validation directly with d2s.validate_xml("./data/aol_rua.xml").

It did have a different relaxed validation error, as it doesn't include a DKIM PolicyEvaluatedType DMARC result when a DKIM is "not.evaluated"

**Comment by jorritfolmer** [comment]
Looks like there is a difference between Splunk python and system python.

**Comment by jorritfolmer** [comment]
Ok this should be fixed in 2.6.0.
I'm converting character sets other than listed [on the libxml2 encoding page](http://xmlsoft.org/encoding.html) to utf-8.
This seems to work, at least for your aol sample.

**Comment by malvidin** [comment]
Hopefully we can get a useful answer.
https://answers.splunk.com/answers/609979/modinput-error-error-processing-windows-1252-encod.html

**Comment by malvidin** [comment]
The fix from 2.6.0 works.
