### ISSUE TITLE
Facing issue in TA-Dmarc app 

### ISSUE THREAD

**Issue by Divyagn92** [jorritfolmer/TA-dmarc#22]
Hi,

I have this app with version 3.1.0 installed on a splunk cloud heavy forwarder version 7.1.3. I am not getting logs from imap server even after multiple password change attempts and configuration change attempts.
The app is connecting to the imap server and GET messages from HTTP is being fetched, after which 404 error messages are being fetched and then finally timeout happens.
Can you please assist me on this ?

**Comment by jorritfolmer** [comment]
The symptoms look like you downloaded the zip file from Github and unzipped it on your HF. Unfortunately Github creates the zip with directory "TA-dmarc-master" instead of just "TA-dmarc". This confuses the add-on as it expects to be named TA-dmarc.
It this is the case, just rename the directory and restart Splunk.

**Comment by Divyagn92** [comment]
Hi Jorrit,

Thanks for the reply. Actually I have downloaded this app from splunkbase and installed on HF. The imap server which I am connecting to, has lakhs of messages and once this app starts to read the messages in queue it is reading the data and giving 200 status code for sometime and this status code gets changed to 404. Attaching the screenshot of logs while reading the data from imap.gmail.com server. Hope this helps to identify the issue.
![error message](https://user-images.githubusercontent.com/48087979/61272360-98c53380-a7c4-11e9-9e19-567e84b8f3d6.png)

**Comment by jorritfolmer** [comment]
Ah ok looks like the IMAP server disconnects you. Possibly because it reaches a timeout before all the emails are read.
Can you experiment with using a batch size of 10 instead of 100? That's configurable in the IMAP input.
