### ISSUE TITLE
getting Argument validation for scheme=dmarc_imap: script running failed (killed by signal 9: Killed).

### ISSUE THREAD

**Issue by infosecfreek** [jorritfolmer/TA-dmarc#25]
@jorritfolmer 
,

I am getting following error when adding input for imap:

Argument validation for scheme=dmarc_imap: script running failed (killed by signal 9: Killed).

Please suggest if any changes are required.

**Comment by jorritfolmer** [comment]
Are you seeing any out-of-memory kills in /var/log/messages? This the only reason I can currently think of why the process is getting actively killed.

**Comment by infosecfreek** [comment]
No I have checked in /var/messages . There is no logs related to memory.

**Comment by jorritfolmer** [comment]
Good news! I've been able to reproduce this error message by dropping network traffic to my test IMAP server. Apparently Splunk will kill the script if it takes longer than 30 seconds to add a new successful input. If I remove the firewall rule, the error will also go away.

**Comment by infosecfreek** [comment]
Thanks for working on this !

It got resolved for me either, but it was different issue for me, the moment I increased the input interval to 3000 from 300, it started working.

**Comment by jorritfolmer** [comment]
Ok I will update the README with your finding, thanks!
