### ISSUE TITLE
Make license clear

### ISSUE THREAD

**Issue by JasperWallace** [jorritfolmer/TA-dmarc#28]
Hi,

Some files (e.g. `TA-dmarc/bin/dmarc/dir2splunk.py`) have a MIT license header, but others don't and there is no `LICENSE` file in the project root and the `app.manifest` file has `null` for the various license fields.

I'm guessing the project is intended to be MIT licensed overall but it would be nice if it was clear.

I'm asking cos I'm hoping to borrow some bits for https://github.com/JasperWallace/django-dmarc2 and wanted to be sure that that was ok.

(sorry if this comes across as a bit nit picky!)

**Comment by jorritfolmer** [comment]
Anything inside dmarc/bin dir is mine and MIT licensed. So borrow right ahead. The rest is mostly boilerplate generated by the Splunk Add-on Builder, and other useful third party libs used. Licensing there depends but mostly Apache I think. This is the reason to not include 1 license in the root.

**Comment by ArcolaJasper** [comment]
Ok, thanks that's great! good luck with TA-dmarc!
