### ISSUE TITLE
Differential processing between IMAP and file directory

### ISSUE THREAD

**Issue by john-9c54a80b** [jorritfolmer/TA-dmarc#3]
I have tested this app on a sample of reports (479 emails) and am getting different import counts apparently due to how the emails are parsed.  Thus, far, it appear to affect primarily Yahoo reports when ingested via the IMAP connection compared to Gmail, Microsoft, and the limited handful of other report sources I have.  I did note that I'm missing 2 reports from Comcast out of a total possible of 26.

Notably, the Yahoo reports (and the two missing Comcast reports) are ingested correctly when I export the attachments to a file directory and point the app to that location instead of IMAP.

For comparison purposes, I set up two different indices (dmarc_test_imap and dmarc_test_dir) and configured the DMARC TA accordingly for each.  My bulk attachment exporter spits out a max of 473 files (zip/gz).  I get an event count of 611 and a unique count of report ID of 473 when using the directory input.  For the IMAP input, I get a max of 376 events and the same value for unique report ID's.  All submitter orgs match in count with the two exceptions noted (233 missing reports for Yahoo and 2 extra Comcast reports, all present in the dmarc_test_dir but missing in dmarc_test_imap).  

I'm using Splunk version 7 and the latest version of the app (2.0.1).  I suspect there may be some kind of formatting issue with the email format from Yahoo and some Comcast.  I would guess other DMARC report providers might also be affected but are outside of my sample range.  I also looked at the XSD comment in your documentation but did not find that as an option in the input configuration, so I am assuming it's off by default.

Let me know what kind of info you might need to see what the cause of the difference in ingesting might be.

**Comment by jorritfolmer** [comment]
Thanks for reporting this issue!
I haven't seen this in my test corpus on IMAP.

Can you forward some of the reports that are missing to me? (My email is in my profile)
Or if that's too sensitive, at least a redacted raw copy of an entire mail with headers and stuff? Perhaps there's an issue with the multitype mime parsing. 
Another helpful bit would be the ta_dmarc_imap.log in DEBUG mode.

The XSD validation is included in v2.1.0 and higher, on Splunkbase it's in "pending review". You can clone it from Github though.

**Comment by john-9c54a80b** [comment]
Sure, sent them over.

**Comment by jorritfolmer** [comment]
Ok think I found the issue. It has to do with the declared Content-Types for the attachments
- application-x-gzip
- application/x-zip-compressed

These are non-standard mime types, in the meaning they don't appear in the [IANA list](https://www.iana.org/assignments/media-types/media-types.xhtml)

Currenly TA-dmarc processes attachments with these types:
- application/zip
- application/gzip
- application/x-gzip
- application/xml
- text/xml

I'll add the non-standard mimetypes to the list of eligible types though.

**Comment by jorritfolmer** [comment]
This issue was fixed in v2.2.0
