### ISSUE TITLE
Upgrade readiness app gives issues with python scripts

### ISSUE THREAD

**Issue by oostlab** [jorritfolmer/TA-dmarc#32]
Dear reader,

Due to EOL splunk 7.2 we want to upgrade to Splunk 8.1. We have used the Splunk readiness app to check for potential problems. According to this app there 1058 python scripts with issues, mainly python v2 to v3 issues, Is there a way to resolve this issuu without manually changing all these files? 

Thanks in advance!

**Comment by jorritfolmer** [comment]
The most recent version of TA-dmarc 3.2.4 works on Splunk 8.1. I assume the readiness app only complains about stuff in `bin/ta_dmarc/aob_py2/`? This directory contains the Splunk libraries for Python 2 compatibility. It won't actually use it in Py3 environments, but will use `bin/ta_dmarc/aob_py3` instead.

**Comment by jorritfolmer** [comment]
I'm closing this issue. TA-dmarc already worked on Splunk 8.1 for many months in many different environments large and small. Well, <cough>, at least the IMAP part <cough>. @COshmyan discovered that this wasn't the case for POP3 and fixed that. Thanks again!

Currently I've been retesting both IMAP and POP3 on Splunk 8.2.0, which was released 2 weeks ago, and found it to be working.
