### ISSUE TITLE
Connectivity issue

### ISSUE THREAD

**Issue by gregorygrevin** [jorritfolmer/TA-dmarc#33]
Splunk Version 8.1.0.1
TA-dmarc Version 3.2.4

Hello,

I am running an all-in-one Splunk where I installed the add-on.
I did a small test by ingesting a local directory, it was a success.

However, when I tried to Configure an IMAP input it is not working :
I have fulfilled an account with a username/password
Then I added an IMAP input with my IMAP server, IMAP Mailbox and all parameters.
I also add a Firewall exception from my Splunk to my exchange server on port TCP/993

When I executed the Splunk command :
` inputlookup ta_dmarc_checkpointer_lookup`

I only saw inputs from my local directory.

Thank you in advance,

**Comment by jorritfolmer** [comment]
Maybe `sourcetype=splunkd` or `sourcetype=ta:dmarc:log` have additional details?

**Comment by gregorygrevin** [comment]
Hello JorritFolmer,

We did a little mistake by configuring the account, we were adding the address mail rather than the domain\user.

Issue solved.

Thank you
