### ISSUE TITLE
Only First DKIM Signature Returned

### ISSUE THREAD

**Issue by malvidin** [jorritfolmer/TA-dmarc#4]
If a report includes a record with multiple DKIM Auth Results, only the first is visible. I'm investigating going directly from XML to JSON with xmljson to keep the entire record.

**Comment by malvidin** [comment]
This is based on the DMARC.org example, but with multiple DKIM records, as permitted.
https://dmarc.org/wiki/FAQ#I_need_to_implement_aggregate_reports.2C_what_do_they_look_like.3F

[rua.dkim2.txt](https://github.com/jorritfolmer/TA-dmarc/files/1544842/rua.dkim2.txt)

**Comment by jorritfolmer** [comment]
Fixed with your JSON PR, now in master.
