### ISSUE TITLE
Provide info for config files generation

### ISSUE THREAD

**Issue by mkrsfcmp** [jorritfolmer/TA-dmarc#41]
Hi.
In current state, the add-on can - as I understand - be only configured by Splunk WebUI. In distributed environment, especially with a separate heavy forwarder layer, you don't even have a GUI in the layer that this add-on's input would operate.
Unfortunately, the passwords.conf file is not very well docummented so we don't know how to generate the encrypted password.
Unfortunately (again) it doesn't seem to be simply working with splunk --show-decrypted so I supposed it's mangled somehow "in the meantime".

**Comment by jorritfolmer** [comment]
Sorry, I don’t have any information about passwords.conf. I use the Splunk Add-on Builder (AoB) to create and handle UI stuff which also includes managing and storing secrets in a Splunk-native way. This means my code just uses the provided abstractions, and never deals or know any implementation detail about the password backend.

**Comment by mkrsfcmp** [comment]
Hmm... Can you then point me to the bit of the code where you handle the password for the IMAP account or whatever that is? I'll try to dig further down from there :-)

**Comment by jorritfolmer** [comment]
Initially the addon is passed the credentials as a Python dict in plain text for the configured input: https://github.com/jorritfolmer/TA-dmarc/blob/a44fa4b21b0c43ee5a598169aa6e3bfa48fa1ff6/bin/input_module_dmarc_imap.py#L37

Which eventually ends up being used here: https://github.com/jorritfolmer/TA-dmarc/blob/a44fa4b21b0c43ee5a598169aa6e3bfa48fa1ff6/bin/dmarc/imap2dir.py#L114

**Comment by mkrsfcmp** [comment]
Thanks for pointing me there. I'll try to dig a bit and see what I can find :-)

**Comment by mkrsfcmp** [comment]
OK. It seems I must have made some typo or something before because it didn't seem to work but it does. The password can be (en/de)crypted by splunk show-decrypted and splunk show-encrypted commands.
It's an encrypted form of a json string containing
`{"password": "your password here"}`
The more interesting thing is that with every "main" encrypted entry in staza 
`[credential:__REST_CREDENTIAL__#TA-dmarc#configs/conf-ta_dmarc_account:<account>``splunk_cred_sep``1:]`
where <account> is the name of the account, containing encrypted json that I wrote above about, there is another entry created called
`[credential:__REST_CREDENTIAL__#TA-dmarc#configs/conf-ta_dmarc_account:<account>``splunk_cred_sep``1:]`
containing encrypted static string of 
`splunk_cred_sep``S``splunk_cred_sep``P``splunk_cred_sep``L``splunk_cred_sep``U``splunk_cred_sep``N``splunk_cred_sep``K``splunk_cred_sep`

So, long story short, to create an input without using the gui, you have to:
1) Create an account - you do it in local/ta_dmarc_account.conf with contents of:

```
[your_account_name]
password = ********
username = your@own.user
```
(yes, these are literal asterisks in the password field, you don't put the password in there.

Then you create a local/passwords.conf file with

```
[credential:__REST_CREDENTIAL__#TA-dmarc#configs/conf-ta_dmarc_account:your_account_name``splunk_cred_sep``1:]
password = <passwordstring1>

[credential:__REST_CREDENTIAL__#TA-dmarc#configs/conf-ta_dmarc_account:your_account_name``splunk_cred_sep``2:]
password = <passwordstring2>
```

Where you create passwordstring1 by using
`splunk show-encrypted --value '{"password": "your_password_here"}'`
(remember to supply your own password ;-)

And create passwordstring2 by using
`splunk show-encrypted --value '``splunk_cred_sep``S``splunk_cred_sep``P``splunk_cred_sep``L``splunk_cred_sep``U``splunk_cred_sep``N``splunk_cred_sep``K``splunk_cred_sep``'
`
(yes, that's a static string).
Finally you create local/inputs.conf with contents:

```
[dmarc_imap://my_input_name]
batch_size = 100
global_account = my_account
imap_mailbox = INBOX
imap_server = my.imap.server
index = test1_or_whatever
interval = 600
output_format = json
resolve_ip = 1
validate_dkim = 0
validate_xml = 1
```

That's for IMAP account. POP3 would be very similar just with a bit different input-specific options (I don't suppose pop3 uses imap_mailbox for example).
Of course after creating the files you'd have to restart your forwarder. I'm wondering though whether it will work at all on a separate HF because the input is supposed to use KV-store which might not be available on HF... But we'll see about that.

**Comment by mkrsfcmp** [comment]
You might want to cut that or redact in any way and include it in the readme :-)

**Comment by jorritfolmer** [comment]
Thanks!

**Comment by mkrsfcmp** [comment]
Hmm... It seems that you can also provide the passwords.com entries in unencrypted form and it should work as well. But the downside is obviously that the passwords are visible in plain text - they will not be encrypted by splunk automatically as pass4SymmKey entries are.
