### ISSUE TITLE
Missing metadata and record information

### ISSUE THREAD

**Issue by malvidin** [jorritfolmer/TA-dmarc#5]
Multiple values from the DMARC aggregate reports are not returned. A couple are listed below.
The DMARC subdomain policy is not returned. Adding it explicitly to the mapping_meta dict or using xmljson could fix this issue.
The policy evaluated reason is not listed, for instances where the policy published is not followed.

**Comment by jorritfolmer** [comment]
Thanks for reporting this! Can you share a sample?

**Comment by malvidin** [comment]
Line 18 from DMARC.org is not exported when processed.
https://dmarc.org/wiki/FAQ#I_need_to_implement_aggregate_reports.2C_what_do_they_look_like.3F
The 'reason' field in line 121 of rua.xsd is not exported.
[rua.policy_reason.txt](https://github.com/jorritfolmer/TA-dmarc/files/1544858/rua.policy_reason.txt)

**Comment by jorritfolmer** [comment]
Thanks, I'll look into it next weekend!

**Comment by jorritfolmer** [comment]
Fixed in 2.3.0, although we'll be going JSON anyway
