### ISSUE TITLE
AOL "not.evaluated" DKIM Authentication Results

### ISSUE THREAD

**Issue by malvidin** [jorritfolmer/TA-dmarc#6]
AOL uses an invalid domain ("not.evaluated") when it cannot perform DKIM checks. Should that whole DKIM auth result be included?

**Comment by jorritfolmer** [comment]
With your additions I think we are converging on these (implicit) principles:

1. data is kept as close as possible to its original format and structure
2. data is added where appropriate for enriching the original data

Adding JSON output realises principle 1, whereas a flat key=val doesn't particularly.
Keeping the AOL auth results also realises principle 1.
Adding report metadata to each record is an example of principle 2, as is reverse resolving source_ip and adding XSD validation results.

What do you think?

**Comment by malvidin** [comment]
I agree.

I thought about splitting the metadata/policy from the records and joining them later, but the size of the somewhat flattened report isn't prohibitive compared to other email logs.

**Comment by jorritfolmer** [comment]
I've expanded our emerging principles in the README.md. Under "Principles". If there's something missing or going sideways in your opinion please let me know.
